// FIX: Completed the truncated file, added missing translations, and included the default export.
// This resolves the "Module has no default export" error.

import type { RarityKey } from '../types';

const gameTranslations = {
    items: {
        'oak_log': { name: 'Oak Log', description: 'A sturdy and common type of wood, ideal for basic crafts.' },
        'acacia_log': { name: 'Acacia Log', description: 'Known for its hard and durable nature, a slightly more challenging wood to work with.' },
        'ebony_log': { name: 'Ebony Log', description: 'Valuable for its dark color and density, used in the making of special items.' },
        'birch_log': { name: 'Birch Log', description: 'A light-colored and flexible wood, often preferred for bows and light furniture.' },
        'bloodwood_log': { name: 'Bloodwood Log', description: 'A rare tree with mystical properties that releases a blood-red sap when cut.' },
        'enchanted_log': { name: 'Enchanted Log', description: 'A sought-after material for magical items, containing a faint glimmer of magic.' },
        'dragontree_log': { name: 'Dragontree Log', description: 'This fire-resistant and nearly unbreakable wood is said to grow where dragons sleep.' },
        'mystic_log': { name: 'Mystic Log', description: 'A wood that seems to come from beyond time and space, with pure magic flowing through its veins.' },
        'stone': { name: 'Stone', description: 'A simple building material found everywhere.' },
        'coal': { name: 'Coal', description: 'An important fuel that burns at high temperatures, enabling the smelting of ores.' },
        'copper_ore': { name: 'Copper Ore', description: 'An easy-to-process, reddish metal. Used for entry-level armor and weapons.' },
        'iron_ore': { name: 'Iron Ore', description: 'Harder and more durable than copper, the cornerstone of civilization.' },
        'steel_ore': { name: 'Steel Ore', description: 'A special blend of iron and carbon, required for higher quality equipment.' },
        'rom_ore': { name: 'Rom Ore', description: 'A rare metal with a unique luster, found around the town of Rom.' },
        'ent_ore': { name: 'Ent Ore', description: 'A living metal that appears to be a fusion of stone and wood from the depths of ancient forests.' },
        'kingdom_ore': { name: 'Kingdom Ore', description: 'An extremely valuable and difficult-to-process ore that can only be mined with royal permission.' },
        'raw_trout': { name: 'Raw Trout', description: 'A delicious fish commonly found in freshwater rivers.' },
        'raw_herring': { name: 'Raw Herring', description: 'An oily and tasty fish, usually caught in schools.' },
        'raw_tuna': { name: 'Raw Tuna', description: 'A large and meaty fish, promising a hearty meal.' },
        'raw_cod': { name: 'Raw Cod', description: 'A popular fish of the cold seas, nutritious and delicious.' },
        'raw_sea_bass': { name: 'Raw Sea Bass', description: 'A sought-after game fish with white flesh.' },
        'raw_salmon': { name: 'Raw Salmon', description: 'A strong fish that swims against the current, its energy reflected in its meat.' },
        'raw_crab': { name: 'Raw Crab', description: 'A sea creature that hides delicious meat under its hard shell.' },
        'cursed_fish': { name: 'Cursed Fish', description: 'It takes courage to touch this fish from deep, dark waters, which has an ominous aura.' },
        'cooked_trout': { name: 'Grilled Trout', description: 'Cooked over a low fire, a simple but satisfying meal. Restores 15% of health.' },
        'cooked_herring': { name: 'Grilled Herring', description: 'Nutritious and delicious. Restores 20% of health.' },
        'cooked_tuna': { name: 'Cooked Tuna', description: 'A hearty fish meat that gives energy. Restores 25% of health.' },
        'cooked_cod': { name: 'Grilled Cod', description: 'The taste of cold waters. Restores 35% of health.' },
        'cooked_sea_bass': { name: 'Grilled Sea Bass', description: 'As if from the hands of a master chef. Restores 45% of health.' },
        'cooked_salmon': { name: 'Grilled Salmon', description: 'A luxurious meal known for its rich taste and color. Restores 60% of health.' },
        'cooked_crab': { name: 'Cooked Crab', description: 'A feast of flavor under its shell. Restores 75% of health.' },
        'scorpion_stinger': { name: 'Scorpion Stinger', description: 'Sharp and poisonous, used in alchemy and arrow making.' },
        'scorpion_venom': { name: 'Scorpion Venom', description: 'A powerful toxin, must be handled with care.' },
        'blood_clot': { name: 'Blood Clot', description: 'A strange component required for some dark rituals and potions.' },
        'goblin_totem': { name: 'Goblin Totem', description: 'A crude but mysterious object used by goblin shamans.' },
        'dirty_coin': { name: 'Dirty Coin', description: 'An old and dirty coin with illegible markings. Perhaps it has some value.' },
        'rusty_iron_piece': { name: 'Rusty Iron Piece', description: 'Must have broken off from an old armor or weapon. Can be melted down and reused.' },
        'bone_particles': { name: 'Bone Particles', description: 'Powdered bones, a part of powerful potions and dark spells.' },
        'snake_skin': { name: 'Snake Skin', description: 'Light and flexible, used in making leather armor.' },
        'poison_sac': { name: 'Poison Sac', description: 'The organ that contains the snake\'s venom. Can be used to poison weapons.' },
        'torn_map_piece': { name: 'Torn Map Piece', description: 'A piece of an old map. Where could the other pieces be?' },
        'chicken_meat': { name: 'Chicken Meat', description: 'A simple but satisfying food.' },
        'cooked_chicken_meat': { name: 'Cooked Chicken', description: 'A light meal. Restores 20% of health.' },
        'chicken_feather': { name: 'Chicken Feather', description: 'Used for fletching arrows and decorations.' },
        'chicken_egg': { name: 'Chicken Egg', description: 'A nutritious and versatile food item.' },
        'healing_herb': { name: 'Healing Herb', description: 'A common plant found in nature with properties to heal minor wounds.' },
        'bear_pelt': { name: 'Bear Pelt', description: 'Thick and warm, this pelt is valuable for making armor for cold climates.' },
        'raw_cow_meat': { name: 'Raw Cow Meat', description: 'Makes an excellent feast when cooked.' },
        'cooked_cow_meat': { name: 'Steak', description: 'A hearty piece of meat. Restores 30% of health.' },
        'deer_horn': { name: 'Deer Horn', description: 'Used for decorative purposes and some special weapon hilts.' },
        'deer_meat': { name: 'Deer Meat', description: 'A low-fat and tasty hunter\'s meal.' },
        'cooked_deer_meat': { name: 'Cooked Deer Meat', description: 'A hunter\'s favorite. Restores 30% of health.' },
        'deer_pelt': { name: 'Deer Pelt', description: 'A soft leather used for light armor and clothing.' },
        'boar_pelt': { name: 'Boar Pelt', description: 'A durable hide known for its tough bristles.' },
        'raw_boar_meat': { name: 'Raw Boar Meat', description: 'A meat with a strong and intense flavor.' },
        'cooked_boar_meat': { name: 'Cooked Boar Meat', description: 'A tough but nutritious meal. Restores 40% of health.' },
        'ivory': { name: 'Ivory', description: 'A valuable and hard-to-carve material, often used in luxury items.' },
        'bat_wing': { name: 'Bat Wing', description: 'An essential part of flight potions and other tricky alchemical mixtures.' },
        'spider_web': { name: 'Spider Web', description: 'Surprisingly strong and sticky, used to make strong threads and fabrics.' },
        'wolf_pelt': { name: 'Wolf Pelt', description: 'The prize of a respected hunter, both warm and giving a wild appearance.' },
        'griffon_feather': { name: 'Griffon Feather', description: 'Dropped from the legendary Griffon, this feather is known for its lightness and durability. Used in making the best arrows.' },
        'sharp_claw': { name: 'Sharp Claw', description: 'Taken from a predator\'s claw, sharp enough to scratch even bone.' },
        'goblin_king_crown': { name: 'Goblin King\'s Crown', description: 'Made of rusty nails and shiny pebbles, a status symbol for a goblin.' },
        'ruh_esansi': { name: 'Soul Essence', description: 'Concentrated spiritual energy left behind by defeated powerful enemies.' },
        'lanet_tozu': { name: 'Cursed Dust', description: 'A fine powder collected from cursed lands, said to bring bad luck to those who touch it.' },
        'oz_tozu': { name: 'Essence Dust', description: 'A shimmering powder used to accelerate alchemical reactions.' },
        'ruh_tozu': { name: 'Spirit Dust', description: 'A fine powder obtained from ghostly remains, used to enchant equipment.' },
        'basic_health_potion': { name: 'Basic Health Potion', description: 'A standard concoction that heals minor wounds.' },
        'greater_health_potion': { name: 'Greater Health Potion', description: 'A more potent healing potion that can be a lifesaver in case of serious injuries.' },
        'copper_bar': { name: 'Copper Bar', description: 'Melted and molded copper, ready for crafting.' },
        'iron_bar': { name: 'Iron Bar', description: 'Purified iron, forming the basis of stronger equipment.' },
        'steel_bar': { name: 'Steel Bar', description: 'Hardened iron, a standard for professional armor and weapons.' },
        'rom_bar': { name: 'Rom Bar', description: 'A heavy bar made of Rom metals, which absorbs light in a strange way.' },
        'ent_bar': { name: 'Ent Bar', description: 'A material difficult to forge, having both the hardness of metal and the flexibility of wood.' },
        'kingdom_bar': { name: 'Kingdom Bar', description: 'A pure metal whose brilliance is dazzling, reserved for the highest tier of equipment.' },
        'worn_helmet': { name: 'Worn Helmet', description: 'At least it keeps the rain off your head. Probably.' },
        'worn_chest': { name: 'Worn Chestplate', description: 'Armor that has seen better days. The holes in it tell a story.' },
        'worn_legs': { name: 'Tattered Trousers', description: 'Made by piecing together different fabric scraps.' },
        'worn_gloves': { name: 'Torn Gloves', description: 'Your fingers are showing, but at least your palms won\'t get calloused.' },
        'worn_boots': { name: 'Worn Boots', description: 'The soles are full of holes, but they\'re better than nothing.' },
        'worn_shield': { name: 'Worn Shield', description: 'It might protect against a few arrows, but it doesn\'t stand much of a chance against a dragon.' },
        'starter_sword': { name: 'Starter Sword', description: 'A simple piece of wood that has been slightly carved. At least it has a pointy end.' },
        'starter_bow': { name: 'Starter Bow', description: 'Consists of a string tied to a flexible branch. It can\'t shoot arrows very far.' },
        'worn_pickaxe': { name: 'Worn Pickaxe', description: 'It might take many strikes to break a stone.' },
        'worn_axe': { name: 'Worn Axe', description: 'Dull but persistent. It will eventually fell that tree.' },
        'aged_fishing_rod': { name: 'Aged Fishing Rod', description: 'An experienced fishing rod that has seen many fish.' },
        'copper_helmet': { name: 'Copper Helmet', description: 'Simple but effective protection. Keeps your head out of trouble.' },
        'copper_chest': { name: 'Copper Chestplate', description: 'Forged from reliable copper, it protects your vital organs.' },
        'copper_legs': { name: 'Copper Greaves', description: 'Provides basic protection without hindering mobility.' },
        'copper_gloves': { name: 'Copper Gloves', description: 'Allows you to grip your weapon more firmly.' },
        'copper_boots': { name: 'Copper Boots', description: 'Strengthens your steps on rough terrain.' },
        'copper_shield': { name: 'Copper Shield', description: 'Light and handy, perfect for novice warriors.' },
        'copper_sword': { name: 'Copper Sword', description: 'Forged from reliable copper, ideal for a novice adventurer.' },
        'copper_bow': { name: 'Copper Bow', description: 'More accurate and powerful than a wooden bow.' },
        'iron_helmet': { name: 'Iron Helmet', description: 'A sturdy helmet designed to withstand the rigors of battle.' },
        'iron_chest': { name: 'Iron Chestplate', description: 'Reinforced with iron plates, it provides serious protection.' },
        'iron_legs': { name: 'Iron Greaves', description: 'The choice of warriors who have gained experience on the battlefield.' },
        'iron_gloves': { name: 'Iron Gauntlets', description: 'Iron-plated gloves that increase the power of your blows.' },
        'iron_boots': { name: 'Iron Boots', description: 'Heavy but protective, they are resistant to all kinds of impacts.' },
        'iron_shield': { name: 'Iron Shield', description: 'A reliable defense tool proven in battle.' },
        'iron_sword': { name: 'Iron Sword', description: 'Made of battle-proven iron, strong and sharp.' },
        'iron_bow': { name: 'Iron Bow', description: 'Reinforced with iron, this bow shoots arrows farther and faster.' },
        'steel_helmet': { name: 'Steel Helmet', description: 'From the hand of a master blacksmith, both protective and stylish.' },
        'steel_chest': { name: 'Steel Chestplate', description: 'Made of polished steel, an armor that strikes fear into enemies.' },
        'steel_legs': { name: 'Steel Greaves', description: 'With its excellent workmanship, it offers both protection and flexibility.' },
        'steel_gloves': { name: 'Steel Gauntlets', description: 'A precise and strong design that protects every finger.' },
        'steel_boots': { name: 'Steel Boots', description: 'These studded boots hold on even the most slippery surfaces.' },
        'steel_shield': { name: 'Steel Shield', description: 'Symbolizes the courage of its owner with the crest on it.' },
        'steel_sword': { name: 'Steel Sword', description: 'From the hand of a master blacksmith, a balanced and deadly steel sword.' },
        'steel_bow': { name: 'Steel Bow', description: 'Hard to draw, but the arrows it shoots can pierce armor.' },
        'rom_helmet': { name: 'Rom Helmet', description: 'A helmet shimmering with the mysterious energy of Rom metals.' },
        'rom_chest': { name: 'Rom Chestplate', description: 'This armor is said to bring unexpected luck to its owner.' },
        'rom_legs': { name: 'Rom Greaves', description: 'Lightens your steps and guides you on the paths of fate.' },
        'rom_gloves': { name: 'Rom Gauntlets', description: 'Everything you hold with these gloves becomes more valuable, even if it doesn\'t turn to gold.' },
        'rom_boots': { name: 'Rom Boots', description: 'Magical boots that always lead you on the right path, to treasure.' },
        'rom_shield': { name: 'Rom Shield', description: 'It deflects blows from its owner and turns them into bad luck.' },
        'rom_sword': { name: 'Rom Sword', description: 'A rare weapon that contains the mysterious power of Rom steel.' },
        'rom_bow': { name: 'Rom Bow', description: 'It is rumored that arrows shot from this bow never miss their target.' },
        'ent_helmet': { name: 'Ent Helmet', description: 'Made from the bark of a living tree, it whispers the wisdom of nature.' },
        'ent_chest': { name: 'Ent Chestplate', description: 'A living armor that contains the power of the ancient forest.' },
        'ent_legs': { name: 'Ent Greaves', description: 'Woven with vines and strong roots, it connects you to the earth.' },
        'ent_gloves': { name: 'Ent Gauntlets', description: 'With these gloves, you feel the power of nature in your hands.' },
        'ent_boots': { name: 'Ent Boots', description: 'Quiets your steps and allows you to walk through the forest without leaving a trace.' },
        'ent_shield': { name: 'Ent Shield', description: 'Made from the trunk of the oldest tree, almost impossible to break.' },
        'ent_sword': { name: 'Ent Sword', description: 'A sword filled with the power of nature, made from the essence of ancient Ents.' },
        'ent_bow': { name: 'Ent Bow', description: 'Made from a living branch, this bow gives life to the arrows it shoots.' },
        'kingdom_helmet': { name: 'Kingdom Helmet', description: 'A crested helmet worn only by the most loyal knights of the kingdom.' },
        'kingdom_chest': { name: 'Kingdom Armor', description: 'The masterpiece of the kingdom\'s blacksmiths, both a work of art and a machine of death.' },
        'kingdom_legs': { name: 'Kingdom Greaves', description: 'An embroidered piece of armor that provides a noble stance and unparalleled protection.' },
        'kingdom_gloves': { name: 'Kingdom Gauntlets', description: 'Stamped with the royal seal, it gives great power to its owner.' },
        'kingdom_boots': { name: 'Kingdom Boots', description: 'Every step taken with these boots carries the weight of a kingdom.' },
        'kingdom_shield': { name: 'Kingdom Shield', description: 'An unshakable shield that represents the honor and strength of the kingdom.' },
        'kingdom_sword': { name: 'Kingdom Sword', description: 'A legendary sword forged by master blacksmiths at the command of kings.' },
        'kingdom_bow': { name: 'Kingdom Bow', description: 'Strung with dragon sinew, the arrows from this bow represent justice.' },
        'recipe_book_rom_helmet': { name: 'Recipe: Rom Helmet', description: 'An ancient scroll explaining how to make a helmet from Rom metals.' },
        'recipe_book_rom_chest': { name: 'Recipe: Rom Chestplate', description: 'An ancient scroll explaining how to make a chestplate from Rom metals.' },
        'recipe_book_rom_legs': { name: 'Recipe: Rom Greaves', description: 'An ancient scroll explaining how to make greaves from Rom metals.' },
        'recipe_book_rom_gloves': { name: 'Recipe: Rom Gauntlets', description: 'An ancient scroll explaining how to make gauntlets from Rom metals.' },
        'recipe_book_rom_boots': { name: 'Recipe: Rom Boots', description: 'An ancient scroll explaining how to make boots from Rom metals.' },
        'recipe_book_rom_shield': { name: 'Recipe: Rom Shield', description: 'An ancient scroll explaining how to make a shield from Rom metals.' },
        'recipe_book_rom_sword': { name: 'Recipe: Rom Sword', description: 'An ancient scroll explaining how to make a sword from Rom metals.' },
        'recipe_book_rom_bow': { name: 'Recipe: Rom Bow', description: 'An ancient scroll explaining how to make a bow from Rom metals.' },
        'recipe_book_ent_helmet': { name: 'Recipe: Ent Helmet', description: 'An ancient scroll explaining how to make a helmet from Ent metals.' },
        'recipe_book_ent_chest': { name: 'Recipe: Ent Chestplate', description: 'An ancient scroll explaining how to make a chestplate from Ent metals.' },
        'recipe_book_ent_legs': { name: 'Recipe: Ent Greaves', description: 'An ancient scroll explaining how to make greaves from Ent metals.' },
        'recipe_book_ent_gloves': { name: 'Recipe: Ent Gauntlets', description: 'An ancient scroll explaining how to make gauntlets from Ent metals.' },
        'recipe_book_ent_boots': { name: 'Recipe: Ent Boots', description: 'An ancient scroll explaining how to make boots from Ent metals.' },
        'recipe_book_ent_shield': { name: 'Recipe: Ent Shield', description: 'An ancient scroll explaining how to make a shield from Ent metals.' },
        'recipe_book_ent_sword': { name: 'Recipe: Ent Sword', description: 'An ancient scroll explaining how to make a sword from Ent metals.' },
        'recipe_book_ent_bow': { name: 'Recipe: Ent Bow', description: 'An ancient scroll explaining how to make a bow from Ent metals.' },
        'recipe_book_kingdom_helmet': { name: 'Recipe: Kingdom Helmet', description: 'An ancient scroll explaining how to make a helmet from Kingdom metals.' },
        'recipe_book_kingdom_chest': { name: 'Recipe: Kingdom Armor', description: 'An ancient scroll explaining how to make an armor from Kingdom metals.' },
        'recipe_book_kingdom_legs': { name: 'Recipe: Kingdom Greaves', description: 'An ancient scroll explaining how to make greaves from Kingdom metals.' },
        'recipe_book_kingdom_gloves': { name: 'Recipe: Kingdom Gauntlets', description: 'An ancient scroll explaining how to make gauntlets from Kingdom metals.' },
        'recipe_book_kingdom_boots': { name: 'Recipe: Kingdom Boots', description: 'An ancient scroll explaining how to make boots from Kingdom metals.' },
        'recipe_book_kingdom_shield': { name: 'Recipe: Kingdom Shield', description: 'An ancient scroll explaining how to make a shield from Kingdom metals.' },
        'recipe_book_kingdom_sword': { name: 'Recipe: Kingdom Sword', description: 'An ancient scroll explaining how to make a sword from Kingdom metals.' },
        'recipe_book_kingdom_bow': { name: 'Recipe: Kingdom Bow', description: 'An ancient scroll explaining how to make a bow from Kingdom metals.' },
    },
    creatures: {
        'akrep': { name: 'Scorpion' },
        'sican': { name: 'Rat' },
        'goblin': { name: 'Goblin' },
        'yilan': { name: 'Snake' },
        'azili_haydut': { name: 'Ferocious Bandit' },
        'tavuk': { name: 'Chicken' },
        'domuz': { name: 'Pig' },
        'fare': { name: 'Mouse' },
        'ayi': { name: 'Bear' },
        'inek': { name: 'Cow' },
        'geyik_rom': { name: 'Deer' },
        'yaban_domuzu_rom': { name: 'Wild Boar' },
        'yarasa': { name: 'Bat' },
        'kacak_avci': { name: 'Poacher' },
        'kimsesiz_haydut': { name: 'Orphaned Bandit' },
        'dev_orumcek': { name: 'Giant Spider' },
        'geyik_kral': { name: 'Deer' },
        'yaban_domuzu_kral': { name: 'Wild Boar' },
        'kral_kurt': { name: 'King Wolf' },
        'griffon': { name: 'Griffon' },
        'goblin_krali': { name: 'Goblin King' }
    },
    mapRegions: {
        'sof_kasabasi': { name: 'Town of Rom', description: 'Once a quiet town, it has now become a haunt for bandits and adventurers. An ideal starting point for hunting.' },
        'liman_kenti': { name: 'Port City', description: 'Doesn\'t seem like a dangerous place... More of a spot where fish and ship merchants roam. Your adventure starts here!' },
        'krallar_sehri': { name: 'Orphaned Lands', description: 'Sinister rumors are circulating in these lands. You\'d better be careful.' },
        'donmuslar': { name: 'Kings\' City', description: 'A legendary castle amidst frozen peaks, where only the bravest can survive.' }
    },
    skills: {
        'gathering': { name: 'Gathering', description: 'Increases gathering efficiency and speed.' },
        'melee_combat': { name: 'Melee Combat', description: 'Increases your mastery of close-quarters combat weapons.' },
        'intuition': { name: 'Intuition', description: 'Improves your ability to sense dangers and notice rare opportunities.' },
        'ranged_combat': { name: 'Ranged Combat', description: 'Increases accuracy and critical strike chance with ranged weapons.' },
        'prowess': { name: 'Prowess', description: 'Improves your overall combat abilities and tactical intelligence.' },
        'woodcutting': { name: 'Woodcutting', description: '' },
        'mining': { name: 'Mining', description: '' },
        'fishing': { name: 'Fishing', description: '' },
        'hunting': { name: 'Hunting', description: '' },
        'alchemy': { name: 'Alchemy', description: '' },
        'smelting': { name: 'Smelting', description: '' },
        'cooking': { name: 'Cooking', description: '' },
        'forge': { name: 'Smithing', description: '' },
    },
    sidebar: {
        character: { label: 'Character' },
        inventory: { label: 'Inventory' },
        professions: { label: 'Professions' },
        map: { label: 'Map' },
        hunting: { label: 'Hunting' },
        settings: { label: 'Settings' },
    },
    recipes: {
        'copper_bar': { name: 'Copper Bar' },
        'iron_bar': { name: 'Iron Bar' },
        'steel_bar': { name: 'Steel Bar' },
        'rom_bar': { name: 'Rom Bar' },
        'ent_bar': { name: 'Ent Bar' },
        'kingdom_bar': { name: 'Kingdom Bar' },
        'craft_worn_helmet': { name: 'Worn Helmet' },
        'craft_worn_chest': { name: 'Worn Chestplate' },
        'craft_worn_legs': { name: 'Tattered Trousers' },
        'craft_worn_gloves': { name: 'Torn Gloves' },
        'craft_worn_boots': { name: 'Worn Boots' },
        'craft_worn_shield': { name: 'Worn Shield' },
        'craft_starter_sword': { name: 'Starter Sword' },
        'craft_starter_bow': { name: 'Starter Bow' },
        'craft_worn_pickaxe': { name: 'Worn Pickaxe' },
        'craft_worn_axe': { name: 'Worn Axe' },
        'craft_aged_rod': { name: 'Aged Fishing Rod' },
        'craft_copper_helmet': { name: 'Copper Helmet' },
        'craft_copper_chest': { name: 'Copper Chestplate' },
        'craft_copper_legs': { name: 'Copper Greaves' },
        'craft_copper_gloves': { name: 'Copper Gloves' },
        'craft_copper_boots': { name: 'Copper Boots' },
        'craft_copper_shield': { name: 'Copper Shield' },
        'craft_copper_sword': { name: 'Copper Sword' },
        'craft_copper_bow': { name: 'Copper Bow' },
        'craft_iron_helmet': { name: 'Iron Helmet' },
        'craft_iron_chest': { name: 'Iron Chestplate' },
        'craft_iron_legs': { name: 'Iron Greaves' },
        'craft_iron_gloves': { name: 'Iron Gauntlets' },
        'craft_iron_boots': { name: 'Iron Boots' },
        'craft_iron_shield': { name: 'Iron Shield' },
        'craft_iron_sword': { name: 'Iron Sword' },
        'craft_iron_bow': { name: 'Iron Bow' },
        'craft_steel_helmet': { name: 'Steel Helmet' },
        'craft_steel_chest': { name: 'Steel Chestplate' },
        'craft_steel_legs': { name: 'Steel Greaves' },
        'craft_steel_gloves': { name: 'Steel Gauntlets' },
        'craft_steel_boots': { name: 'Steel Boots' },
        'craft_steel_shield': { name: 'Steel Shield' },
        'craft_steel_sword': { name: 'Steel Sword' },
        'craft_steel_bow': { name: 'Steel Bow' },
        'craft_rom_helmet': { name: 'Rom Helmet' },
        'craft_rom_chest': { name: 'Rom Chestplate' },
        'craft_rom_legs': { name: 'Rom Greaves' },
        'craft_rom_gloves': { name: 'Rom Gauntlets' },
        'craft_rom_boots': { name: 'Rom Boots' },
        'craft_rom_shield': { name: 'Rom Shield' },
        'craft_rom_sword': { name: 'Rom Sword' },
        'craft_rom_bow': { name: 'Rom Bow' },
        'craft_ent_helmet': { name: 'Ent Helmet' },
        'craft_ent_chest': { name: 'Ent Chestplate' },
        'craft_ent_legs': { name: 'Ent Greaves' },
        'craft_ent_gloves': { name: 'Ent Gauntlets' },
        'craft_ent_boots': { name: 'Ent Boots' },
        'craft_ent_shield': { name: 'Ent Shield' },
        'craft_ent_sword': { name: 'Ent Sword' },
        'craft_ent_bow': { name: 'Ent Bow' },
        'craft_kingdom_helmet': { name: 'Kingdom Helmet' },
        'craft_kingdom_chest': { name: 'Kingdom Armor' },
        'craft_kingdom_legs': { name: 'Kingdom Greaves' },
        'craft_kingdom_gloves': { name: 'Kingdom Gauntlets' },
        'craft_kingdom_boots': { name: 'Kingdom Boots' },
        'craft_kingdom_shield': { name: 'Kingdom Shield' },
        'craft_kingdom_sword': { name: 'Kingdom Sword' },
        'craft_kingdom_bow': { name: 'Kingdom Bow' },
        'cook_trout': { name: 'Grilled Trout' },
        'cook_herring': { name: 'Grilled Herring' },
        'cook_tuna': { name: 'Cooked Tuna' },
        'cook_cod': { name: 'Grilled Cod' },
        'cook_sea_bass': { name: 'Grilled Sea Bass' },
        'cook_salmon': { name: 'Grilled Salmon' },
        'cook_crab': { name: 'Cooked Crab' },
        'cook_chicken_meat': { name: 'Cooked Chicken' },
        'cook_cow_meat': { name: 'Steak' },
        'cook_deer_meat': { name: 'Cooked Deer Meat' },
        'cook_boar_meat': { name: 'Cooked Boar Meat' },
    }
};

const rarityTranslations: Record<RarityKey, string> = {
    'common': 'Common',
    'uncommon': 'Uncommon',
    'rare': 'Rare',
    'epic': 'Epic',
    'legendary': 'Legendary'
};

const en = {
    ui: {
        // Auth & General
        login: 'Login',
        register: 'Register',
        username: 'Username',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        passwordsDoNotMatch: 'Passwords do not match.',
        invalidCredentials: 'Invalid username or password.',
        registrationFailed: 'Registration failed. Username may already be taken.',
        unexpectedError: 'An unexpected error occurred.',
        createAccount: 'Create Account',
        authTitle: 'Idle Realms',
        authSubtitle: 'Forge Your Legend',
        logout: 'Logout',
        logoutConfirmTitle: 'Logout',
        logoutConfirmMessage: 'Are you sure you want to log out?',
        back: 'Back',
        level: 'Level',
        level_short: 'Lvl.',
        levelWithNumber: 'Level {level}',
        yes: 'Yes',
        no: 'No',

        // Character Screens
        characterSelectionTitle: 'Select a Hero',
        welcomeBack: 'Welcome back, {username}. Select a hero to continue your adventure.',
        play: 'Play',
        newCharacter: '+ Create New Character',
        maxCharactersReached: 'You have reached the maximum number of characters (5/5).',
        deleteCharacter: 'Delete Character',
        deleteCharacterConfirmTitle: 'Delete Character',
        deleteCharacterConfirmMessage: 'Are you sure you want to permanently delete the character <strong>\'{characterName}\'</strong> and all related data?<br/><br/><span class="font-bold text-[var(--accent-red)]">This action cannot be undone.</span>',
        yesDelete: 'Yes, Delete',
        noCancel: 'No, Cancel',
        syncCharacters: 'Sync',
        syncing: 'Syncing...',
        syncSuccess: 'Characters synced successfully!',
        syncFailed: 'Sync with cloud failed: {error}. Showing offline characters.',
        createHeroTitle: 'Create a New Hero',
        createHeroDescription: 'Give a name to your hero who will embark on an adventure. Remember, this name will echo in legends!',
        characterName: 'Character Name',
        characterNamePlaceholder: 'Give your hero a name...',
        nameMinLength: 'Character name must be at least 3 letters long.',
        startAdventure: 'Start Adventure',
        creating: 'Creating...',
        charSelectConfirmTitle: 'Return to Character Selection',
        charSelectConfirmMessage: 'Are you sure you want to return to the character selection screen? Your current progress will be saved automatically.',
        yesReturn: 'Yes, Return',
        changeCharacter: 'Change Character',

        // Loading States
        loadingSession: 'Checking Session...',
        loadingCharacters: 'Syncing Characters...',
        loadingGameData: 'Loading Game Data...',

        // Settings
        settings: 'Settings',
        language: 'Language',
        theme: 'Theme',
        themeMedieval: 'Medieval (Dark)',
        themeLight: 'Light',
        colorblindMode: 'Colorblind Mode',
        colorblindDesc: 'Adjusts color contrast and palette.',
        performanceMode: 'Performance Mode',
        performanceDesc: 'Improves performance by reducing visual effects.',
        resetAccount: 'Reset Account',
        resetDesc: 'Permanently delete all your progress and characters.',
        resetBtn: 'Reset Account',
        preferences: 'Preferences',
        appearance: 'Appearance',
        accessibility: 'Accessibility',
        account: 'Account',
        levelUpNotifications: 'Level Up Notifications',
        levelUpNotificationsDesc: 'Show a notification when your character levels up.',
        milestoneNotifications: 'Profession Milestone Notifications',
        milestoneNotificationsDesc: 'Show a notification when a profession levels up.',
        sessionManagement: 'Session Management',
        sessionManagementDesc: 'Return to the character selection screen to play with another character or create a new one.',
        dataManagement: 'Data Management',
        dataManagementDesc: 'If you are experiencing issues with this character, you can clear all local game data stored in your browser.',
        clearLocalData: 'Clear Local Data',
        clearLocalDataTitle: 'Clear Local Data',
        clearLocalDataMessage: 'Are you sure? All your local progress for this character will be deleted. If you have a cloud save, it will be loaded on your next login.',
        yesClear: 'Yes, Clear',

        // Game Context Notifications & Logs
        levelUpMessage: 'Congratulations! You have reached level {level}!',
        skillLevelUpMessage: 'Your {skillName} skill has reached level {level}!',
        actionStopped: '{actionName} action stopped. Gains: {items} items, {xp} XP.',
        rareFind: 'A rare find! You obtained 1x {itemName}!',
        craftingStoppedNoMats: 'Crafting of {recipeName} stopped: Out of materials!',
        notEnoughGold: 'Not enough gold!',
        travelStarted: 'Travel to {destinationName} has begun...',
        travelFinished: 'You have arrived at {destinationName}!',
        gameSavedCloud: 'Game successfully saved to the cloud!',
        gameSavedCloudAndLocal: 'Game saved to cloud and locally. ({time})',
        cloudSaveFailed: 'Cloud save failed! Game has been saved locally.',
        cloudSaveError: 'ERROR: Could not save to cloud. ({error})',
        statsUpdated: 'Stats have been updated!',
        inventoryFull: 'Inventory is full!',
        itemUsedHeal: 'Used {itemName}, restored {healValue} health.',
        settingsUpdated: 'Settings updated.',
        offlineProgressSynced: 'Offline progress synced with the cloud!',
        offlineSyncFailed: 'Failed to sync offline progress to the cloud.',
        huntingNotReady: 'You are not ready to hunt. You must be in a suitable area and have a weapon equipped.',
        huntingActionCancel: 'Hunting session stopped to start a profession.',
        huntingDurationRefreshed: 'Hunt duration has been refreshed.',
        defeatedAndReturning: 'You have been defeated! Returning with the loot you gathered.',
        returningFromHunt: 'Returning from the hunt. Loot will be in your inventory shortly!',
        returnedFromHunt: 'You have returned from the hunt and collected your loot.',
        offlineHuntSummarySuccess: 'While you were away, you hunted {encounters} creatures, earning {lootCount} loot and {xp} XP!',
        offlineHuntSummaryDefeat: 'You were defeated while hunting offline! You returned with the {lootCount} loot you had gathered.',
        offlineGatheringSummary: 'While offline, you produced {itemCount} {itemName} and gained {xpGained} profession XP!',

        // Header
        openMenu: 'Open Menu',
        health: 'Health',
        xpUnit: 'XP',
        gold: 'Gold',
        saveGameTitle: 'Save Game',
        saving: 'Saving...',
        saveGame: 'Save',
        justNow: 'just now',
        notifications: 'Notifications',
        saveGameMobile: 'Save Game',

        // Notifications Panel
        notificationsTitle: 'Notifications',
        noNewNotifications: 'No new notifications.',
        clearAll: 'Clear All',
        secondsAgo: '{count}s ago',
        minutesAgo: '{count}m ago',
        hoursAgo: '{count}h ago',
        daysAgo: '{count}d ago',
        monthsAgo: '{count}mo ago',
        yearsAgo: '{count}y ago',

        // Header Action Display
        goToHuntingDetails: 'Go to {huntingLabel} details',
        activeActionHunting: 'Active Action: Hunting',
        travelingTo: 'Traveling to {destinationName}',
        traveling: 'Traveling',
        goToProfessionDetails: 'Go to profession details',
        activeActionProfession: 'Active Action: {actionName}',

        // Character Panel
        character: 'Character',
        profile: 'Profile',
        statistics: 'Statistics',
        skills: 'Skills',
        professions: 'Professions',
        skillToCome: 'A description for this skill will be added soon.',

        // Combat Stats
        combatValues: 'Combat Values',
        attackPower: 'Attack Power',
        defense: 'Defense',
        critChance: 'Crit Chance',
        critDamage: 'Crit Damage',
        evasionChance: 'Evasion Chance',
        
        // Stat Names & Descriptions
        stat_strength: 'Strength',
        stat_agility: 'Agility',
        stat_tactics: 'Tactics',
        stat_endurance: 'Endurance',
        stat_charisma: 'Charisma',
        stat_luck: 'Luck',
        stat_strength_desc: 'Increases physical attack power and carry capacity.',
        stat_agility_desc: 'Improves attack speed, critical hit chance, and evasion.',
        stat_tactics_desc: 'Increases battlefield intelligence, critical damage bonus, and effectiveness of special abilities.',
        stat_endurance_desc: 'Increases maximum health points and physical defense.',
        stat_charisma_desc: 'Increases persuasion and trading skills. Can open unexpected doors.',
        stat_luck_desc: 'Increases critical hit chance and the likelihood of finding rare items.',
        statPoints: 'Points to distribute: {points}',
        reset: 'Reset',
        saveChanges: 'Save Changes',
        detailsTooltip: 'Hover for details',
        base: 'Base:',
        assigned: 'Assigned:',
        equipment: 'Equipment:',
        profession: 'Profession:',
        total: 'Total:',
        
        // Inventory
        inventory: 'Inventory',
        allItems: 'All',
        potions: 'Potions',
        materials: 'Materials',
        miscItems: 'Misc',
        searchItems: 'Search items...',
        slot: 'slot',
        sort: 'Sort',
        betterEquipment: 'Better equipment!',
        equip: 'Equip',
        use: 'Use',
        sell: 'Sell',

        // Item Types
        itemType_equipment: 'Equipment',
        itemType_potion: 'Potion',
        itemType_material: 'Material',
        itemType_misc: 'Miscellaneous',
        itemType_tool: 'Tool',
        itemType_weapon: 'Weapon',
        itemType_helmet: 'Helmet',
        itemType_chest: 'Chestplate',
        itemType_legs: 'Greaves',
        itemType_boots: 'Boots',
        itemType_gloves: 'Gloves',
        itemType_shield: 'Shield',
        
        // Equipment Slots
        slot_helmet: 'Helmet',
        slot_chest: 'Chest',
        slot_legs: 'Legs',
        slot_boots: 'Boots',
        slot_weapon: 'Weapon',
        slot_shield: 'Shield',
        slot_gloves: 'Gloves',
        
        // Equipment Picker
        slotAndType: '{slotType} Slot',
        equipped: 'Equipped',
        unequip: 'Unequip',
        noItemsForSlot: 'No suitable items for this slot.',
        better: 'Better',
        worse: 'Worse',

        // Skills Page
        gathering: 'Gathering',
        production: 'Production',
        gatheringDesc: 'Develop these skills to gather resources and obtain materials.',
        productionDesc: 'Turn the materials you gather into valuable items.',
        backToSkills: 'Back',
        xpProgress: 'XP Progress',
        gatheringEfficiency: 'Gathering Efficiency',
        toolBonus: 'Tool Bonus',
        speed: 'Speed',
        xpGain: 'XP Gain',
        gatherTime: 'Gather Time',
        craftTime: 'Craft Time',
        gather: 'Gather',
        craft: 'Craft',
        stop: 'Stop',
        locked: 'Locked',
        noRecipesFilter: 'No recipes to show for this filter.',
        noRecipesSkill: 'There are no crafting recipes for this profession yet.',
        noResourcesSkill: 'There are no resources to gather in this profession.',

        // Smithing Filters
        filterAll: 'All',
        filterTools: 'Tools',
        filterWeapons: 'Weapons',
        filterHelmets: 'Helmets',
        filterChests: 'Chests',
        filterLegs: 'Legs',
        filterBoots: 'Boots',
        filterGloves: 'Gloves',

        // Hunting Page
        huntPreparation: 'Hunt Preparation',
        safetyWarningSafe: 'Your hunting level is sufficient for this area, you can hunt safely.',
        safetyWarningDanger: 'Your hunting level is low, reducing your chances of catching rare creatures and loot, with a risk of death.',
        wildernessOf: 'Wilderness of {regionName}',
        exploreCreaturesAndLoot: 'Explore the creatures and potential loot in this region.',
        possibleLoot: 'Possible Loot',
        requirements: 'Requirements',
        reqWeapon: 'You must have a weapon equipped.',
        reqCreatures: 'There must be creatures to hunt in the area.',
        supportSlot: 'Support Slot',
        selectItem: 'Select Item',
        supportSlotDesc: 'Automatically used when your health drops below 30%.',
        selectSupportItem: 'Select Support Item',
        noSuitableItems: 'No suitable items in inventory.',
        removeSelectedItem: 'Remove Selected Item',
        startHunt: 'Start Hunt',
        huntInProgress: 'Hunt in Progress',
        returningFromHuntTitle: 'Returning from Hunt',
        returningToTown: 'Returning to Town...',
        lootAndXpSoon: 'Loot and experience points will be added shortly.',
        timeRemaining: 'TIME REMAINING',
        support: 'SUPPORT',
        health_cap: 'HEALTH',
        activeSupport: 'Active Support: {itemName}',
        refresh: 'Refresh',
        return: 'Return',
        fighting: 'Fighting: {creatureName}',
        exploringTheWilderness: 'Exploring the wilderness...',
        keepAnEyeOnTheLog: 'Follow the hunt log for details.',
        searchingForPrey: 'Searching for Prey...',
        collectedLoot: 'Collected Loot',
        noLootCollected: 'No loot collected yet.',
        huntingLog: 'Hunting Log',
        lootObtained: 'Obtained {quantity}x {itemName}.',
        noLootFound: 'Nothing valuable was found on the creature.',
        defeatedAndReturningLog: 'You were injured and are retreating to town...',
        returningFromHuntLog: 'Returning from the hunt. Total loot will be added to inventory.',
        huntStarted: 'The hunt has begun. Searching for creatures in the area.',
        noSuitableCreaturesLeft: 'No creatures suitable for your level left in this area.',
        encounteredCreature: 'You encountered a wild {creatureName}!',
        itemUsedHealInHunt: 'Used {itemName} and restored {healAmount} health.',
        searchingForNewPrey: 'Searching for new prey...',
        huntFlavor_1: 'You look around...',
        huntFlavor_2: 'You hear a rustle, but it\'s just the wind.',
        huntFlavor_3: 'For a moment, you thought you saw a shadow. Your eyes are playing tricks on you.',
        huntFlavor_4: 'You\'re looking for tracks...',
        huntFlavor_5: 'Silence... too much silence.',
        huntFlavor_6: 'A broken branch, something must be nearby.',
        huntFlavor_7: 'A distant howl echoed.',
        
        // Map Page
        worldMap: 'World Map',
        exploreTheWorld: 'Explore the World',
        exploreTheWorldDesc: 'New hunting grounds and adventures await you.',
        openWorldMap: 'Open World Map',
        backToMap: 'Back to Map',
        creaturesInRegion: 'Creatures in Region',
        noCreaturesHere: 'No known creatures in this region.',
        travelInfo: 'Travel Information',
        levelReqWithColon: 'Required Level:',
        cost: 'Cost:',
        duration: 'Duration:',
        travelToRegion: 'Travel to this Region',
        closeMap: 'Close Map',
        seeDetails: 'See details: {regionName}',
        clickForDetails: 'Click for details',
        youAreHere: 'You are here',
        youAreIn: 'You are in {regionName}',

        // Profession Bonus Descriptions
        profBonus_strength: 'Your mastery in this profession increases your physical attack power and carrying capacity.',
        profBonus_agility: 'Your mastery in this profession improves your attack speed, critical strike, and evasion chance.',
        profBonus_tactics: 'Your mastery in this profession increases your critical damage bonus and the effectiveness of special abilities.',
        profBonus_endurance: 'Your mastery in this profession increases your maximum health points and physical defense.',
        profBonus_charisma: 'Your mastery in this profession increases your persuasion and trading abilities.',
        profBonus_luck: 'Your mastery in this profession increases your critical strike and rare item find chance.',

        // Encounter Messages
        encounterPrelude_1: 'A rustle is heard from the bushes...',
        encounterPrelude_2: 'A shadow appears on the horizon.',
        encounterPrelude_3: 'A sharp cry broke the silence.',
        encounterPrelude_4: 'The ground trembles slightly, something is nearby.',
        encounterPrelude_5: 'You noticed a movement up ahead.',
        encounterPrelude_6: 'You found fresh tracks, the prey must be close.',
        encounterPrelude_7: 'You caught a scent of prey while looking around.',
        encounterPrelude_8: 'A moment of silence, like the calm before the storm...',
        encounterPrelude_9: 'You saw a puddle nearby, animals might come for a drink.',
        encounterPrelude_10: 'You heard a strange, unnatural sound.',
        encounterPrelude_11: 'A shadow quickly passed by you.',
        encounterPrelude_12: 'You saw a scorpion, you are approaching.',
        encounterPrelude_13: 'You saw a {creatureName} while looking around.',
        
        encounterSuccessMessage_1: 'After a tough fight, you hunted the {creatureName}, but took {damageTaken} damage.',
        encounterSuccessMessage_2: 'With a quick attack, you hunted the {creatureName} and took {damageTaken} damage.',
        encounterSuccessMessage_3: 'After a tough fight, the {creatureName} was hunted. You took {damageTaken} damage in the process.',
        encounterSuccessMessage_4: 'After a careful pursuit, the {creatureName} was hunted. You took {damageTaken} damage in the conflict.',
        encounterSuccessMessage_5: 'The {creatureName} was caught off guard by your attack and was hunted. This cost you only {damageTaken} damage.',
        encounterSuccessMessage_6: 'At the end of a long chase, the {creatureName} tired out and became prey. You took {damageTaken} damage.',
        encounterSuccessMessage_7: 'Approaching silently, you caught the {creatureName} off guard! This cost you {damageTaken} damage.',
        encounterSuccessMessage_8: 'After a heroic battle, the {creatureName} was defeated. You took {damageTaken} damage.',
    },
    game: gameTranslations,
    rarity: rarityTranslations,
};

export default en;
