// FIX: Changed import from non-existent 'Rarity' to the correct 'RarityKey' type.
import type { Item, RarityKey, Stats } from '../types';

// FIX: Updated the keys to match the RarityKey type for type safety and consistency.
export const rarityColors: Record<RarityKey, string> = {
    'common': '#9ca3af',      // stone-400
    'uncommon': '#34d399',      // emerald-400
    'rare': '#60a5fa',         // blue-400
    'epic': '#a78bfa',          // violet-400
    'legendary': '#f59e0b',     // amber-500
};

// FIX: Updated all 'rarity' values from Turkish strings to RarityKey enum values to match the Item type definition.
export const itemDatabase: Record<string, Item> = {
    // === GATHERING MATERIALS ===
    // Woodcutting
    'oak_log': { id: 'oak_log', name: 'Meşe Odunu', quantity: 0, icon: 'https://files.catbox.moe/bqezuv.png', type: 'material', rarity: 'common', description: 'Sağlam ve yaygın bir odun türü, temel zanaatlar için ideal.' },
    'acacia_log': { id: 'acacia_log', name: 'Akasya Odunu', quantity: 0, icon: 'https://files.catbox.moe/bndym9.png', type: 'material', rarity: 'common', description: 'Sert ve dayanıklı yapısıyla bilinen, işlenmesi biraz daha zor bir odun.' },
    'ebony_log': { id: 'ebony_log', name: 'Abanoz Odunu', quantity: 0, icon: 'https://files.catbox.moe/nvqdwf.png', type: 'material', rarity: 'uncommon', description: 'Koyu rengi ve yoğunluğuyla değerli, özel eşyaların yapımında kullanılır.' },
    'birch_log': { id: 'birch_log', name: 'Huş Odunu', quantity: 0, icon: 'https://files.catbox.moe/9x3dsr.png', type: 'material', rarity: 'uncommon', description: 'Açık renkli ve esnek bir odun, genellikle yay ve hafif mobilyalarda tercih edilir.' },
    'bloodwood_log': { id: 'bloodwood_log', name: 'Kan Odunu', quantity: 0, icon: 'https://files.catbox.moe/4mxfdv.png', type: 'material', rarity: 'rare', description: 'Kesildiğinde kan kırmızısı bir özsu salan, mistik özelliklere sahip nadir bir ağaç.' },
    'enchanted_log': { id: 'enchanted_log', name: 'Efsunlu Odun', quantity: 0, icon: 'https://files.catbox.moe/on04oo.png', type: 'material', rarity: 'rare', description: 'İçinde hafif bir sihir parıltısı barındıran, büyülü eşyalar için aranan bir malzeme.' },
    'dragontree_log': { id: 'dragontree_log', name: 'Ejderha Ağacı Odunu', quantity: 0, icon: 'https://files.catbox.moe/vl81ik.png', type: 'material', rarity: 'epic', description: 'Ateşe dayanıklı ve neredeyse kırılmaz olan bu odun, efsanelere göre ejderhaların uyuduğu yerlerde büyür.' },
    'mystic_log': { id: 'mystic_log', name: 'Mistik Odun', quantity: 0, icon: 'https://files.catbox.moe/b99lgn.png', type: 'material', rarity: 'epic', description: 'Damarlarında saf sihir akan, zaman ve mekanın ötesinden gelmiş gibi görünen bir odun.' },

    // Mining
    'stone': { id: 'stone', name: 'Taş', quantity: 0, icon: 'https://files.catbox.moe/v18l2q.png', type: 'material', rarity: 'common', description: 'Her yerde bulunan basit bir yapı malzemesi.' },
    'coal': { id: 'coal', name: 'Kömür', quantity: 0, icon: 'https://files.catbox.moe/15muc6.png', type: 'material', rarity: 'common', description: 'Yüksek ısıda yanarak madenlerin eritilmesini sağlayan önemli bir yakıt.' },
    'copper_ore': { id: 'copper_ore', name: 'Bakır Cevheri', quantity: 0, icon: 'https://files.catbox.moe/hlgk8e.png', type: 'material', rarity: 'common', description: 'İşlenmesi kolay, kırmızımsı bir metal. Başlangıç seviyesi zırh ve silahlar için kullanılır.' },
    'iron_ore': { id: 'iron_ore', name: 'Demir Cevheri', quantity: 0, icon: 'https://files.catbox.moe/6e2j38.png', type: 'material', rarity: 'uncommon', description: 'Bakırdan daha sert ve dayanıklı olan, medeniyetin temel taşı.' },
    'steel_ore': { id: 'steel_ore', name: 'Çelik Cevheri', quantity: 0, icon: 'https://files.catbox.moe/5e8csk.png', type: 'material', rarity: 'uncommon', description: 'Demir ve karbonun özel bir karışımı, daha kaliteli ekipmanlar için gereklidir.' },
    'rom_ore': { id: 'rom_ore', name: 'Rom Cevheri', quantity: 0, icon: 'https://files.catbox.moe/3gvwvg.png', type: 'material', rarity: 'rare', description: 'Rom Kasabası civarında bulunan, kendine özgü bir parlaklığa sahip nadir bir metal.' },
    'ent_ore': { id: 'ent_ore', name: 'Ent Cevheri', quantity: 0, icon: 'https://files.catbox.moe/q0s08z.png', type: 'material', rarity: 'rare', description: 'Kadim ormanların derinliklerinde, taş ve ağacın birleşimiyle oluşmuş gibi görünen canlı bir metal.' },
    'kingdom_ore': { id: 'kingdom_ore', name: 'Krallık Cevheri', quantity: 0, icon: 'https://files.catbox.moe/071w7i.png', type: 'material', rarity: 'epic', description: 'Sadece kraliyet izniyle çıkarılabilen, son derece değerli ve işlenmesi zor bir cevher.' },

    // Fishing
    'raw_trout': { id: 'raw_trout', name: 'Çiğ Alabalık', quantity: 0, icon: 'https://files.catbox.moe/di34wx.png', type: 'material', rarity: 'common', description: 'Tatlı su nehirlerinde sıkça bulunan lezzetli bir balık.' },
    'raw_herring': { id: 'raw_herring', name: 'Çiğ Ringa Balığı', quantity: 0, icon: 'https://files.catbox.moe/hlfl0k.png', type: 'material', rarity: 'common', description: 'Yağlı ve lezzetli, genellikle sürüler halinde avlanan bir balık.' },
    'raw_tuna': { id: 'raw_tuna', name: 'Çiğ Ton Balığı', quantity: 0, icon: 'https://files.catbox.moe/wvajri.png', type: 'material', rarity: 'common', description: 'Büyük ve etli bir balık, doyurucu bir öğün vaat ediyor.' },
    'raw_cod': { id: 'raw_cod', name: 'Çiğ Morina', quantity: 0, icon: 'https://files.catbox.moe/y7b55m.png', type: 'material', rarity: 'uncommon', description: 'Soğuk denizlerin popüler balığı, besleyici ve lezzetli.' },
    'raw_sea_bass': { id: 'raw_sea_bass', name: 'Çiğ Levrek', quantity: 0, icon: 'https://files.catbox.moe/2c3kop.png', type: 'material', rarity: 'uncommon', description: 'Beyaz etli, aranan bir av balığı.' },
    'raw_salmon': { id: 'raw_salmon', name: 'Çiğ Somon', quantity: 0, icon: 'https://files.catbox.moe/ugsdst.png', type: 'material', rarity: 'rare', description: 'Akıntıya karşı yüzen güçlü balık, enerjisi etine yansımış.' },
    'raw_crab': { id: 'raw_crab', name: 'Çiğ Yengeç', quantity: 0, icon: 'https://files.catbox.moe/smxw0d.png', type: 'material', rarity: 'rare', description: 'Sert kabuğunun altında lezzetli etler saklayan bir deniz canlısı.' },
    'cursed_fish': { id: 'cursed_fish', name: 'Lanetli Balık', quantity: 0, icon: 'https://files.catbox.moe/c4w3k0.png', type: 'material', rarity: 'epic', description: 'Derin ve karanlık sulardan gelen, uğursuz bir auraya sahip bu balığa dokunmak cesaret ister.' },
    
    // Cooked Fish
    'cooked_trout': { id: 'cooked_trout', name: 'Izgara Alabalık', quantity: 0, icon: 'https://files.catbox.moe/gmf71y.png', type: 'potion', rarity: 'common', healAmount: 0.15, description: 'Hafif ateşte pişirilmiş, basit ama doyurucu bir yemek. Canın %15\'ini yeniler.' },
    'cooked_herring': { id: 'cooked_herring', name: 'Izgara Ringa Balığı', quantity: 0, icon: 'https://files.catbox.moe/f2t8v6.png', type: 'potion', rarity: 'common', healAmount: 0.20, description: 'Besleyici ve lezzetli. Canın %20\'sini yeniler.' },
    'cooked_tuna': { id: 'cooked_tuna', name: 'Pişmiş Ton Balığı', quantity: 0, icon: 'https://files.catbox.moe/unkxpe.png', type: 'potion', rarity: 'common', healAmount: 0.25, description: 'Enerji veren doyurucu bir balık eti. Canın %25\'ini yeniler.' },
    'cooked_cod': { id: 'cooked_cod', name: 'Izgara Morina', quantity: 0, icon: 'https://files.catbox.moe/l0g30y.png', type: 'potion', rarity: 'uncommon', healAmount: 0.35, description: 'Soğuk suların lezzeti. Canın %35\'ini yeniler.' },
    'cooked_sea_bass': { id: 'cooked_sea_bass', name: 'Izgara Levrek', quantity: 0, icon: 'https://files.catbox.moe/wvg48y.png', type: 'potion', rarity: 'uncommon', healAmount: 0.45, description: 'Usta bir aşçının elinden çıkmış gibi. Canın %45\'ini yeniler.' },
    'cooked_salmon': { id: 'cooked_salmon', name: 'Izgara Somon', quantity: 0, icon: 'https://files.catbox.moe/3kuk7i.png', type: 'potion', rarity: 'rare', healAmount: 0.60, description: 'Zengin tadı ve rengiyle bilinen lüks bir yemek. Canın %60\'ını yeniler.' },
    'cooked_crab': { id: 'cooked_crab', name: 'Pişmiş Yengeç', quantity: 0, icon: 'https://files.catbox.moe/oyfmco.png', type: 'potion', rarity: 'rare', healAmount: 0.75, description: 'Kabuğunun altında lezzet şöleni var. Canın %75\'ini yeniler.' },

    // === HUNTING DROPS ===
    'scorpion_stinger': { id: 'scorpion_stinger', name: 'Akrep İğnesi', quantity: 0, icon: 'https://files.catbox.moe/jlka9n.png', type: 'material', rarity: 'common', description: 'Keskin ve zehirli, simyada ve ok yapımında kullanılır.' },
    'scorpion_venom': { id: 'scorpion_venom', name: 'Akrep Zehri', quantity: 0, icon: 'https://files.catbox.moe/yai58x.png', type: 'material', rarity: 'common', description: 'Güçlü bir toksin, dikkatli işlenmelidir.' },
    'blood_clot': { id: 'blood_clot', name: 'Kan Pıhtısı', quantity: 0, icon: 'https://files.catbox.moe/vs6lky.png', type: 'material', rarity: 'common', description: 'Bazı karanlık ritüeller ve iksirler için gereken garip bir bileşen.' },
    'goblin_totem': { id: 'goblin_totem', name: 'Goblin Totemi', quantity: 0, icon: 'https://files.catbox.moe/myal68.png', type: 'material', rarity: 'uncommon', description: 'Goblin şamanları tarafından kullanılan, kaba saba ama gizemli bir obje.' },
    'dirty_coin': { id: 'dirty_coin', name: 'Kirli Para', quantity: 0, icon: 'https://files.catbox.moe/gn275n.png', type: 'material', rarity: 'uncommon', description: 'Üzerinde ne olduğu belli olmayan, eski ve kirli bir sikke. Belki de bir değeri vardır.' },
    'rusty_iron_piece': { id: 'rusty_iron_piece', name: 'Paslı Demir Parçası', quantity: 0, icon: 'https://files.catbox.moe/xitysz.png', type: 'material', rarity: 'uncommon', description: 'Eski bir zırhtan veya silahtan kopmuş olmalı. Eritilerek yeniden kullanılabilir.' },
    'bone_particles': { id: 'bone_particles', name: 'Kemik Parçacıkları', quantity: 0, icon: 'https://files.catbox.moe/i3y4bn.png', type: 'material', rarity: 'uncommon', description: 'Toz haline gelmiş kemikler, güçlü iksirlerin ve karanlık büyülerin bir parçası.' },
    'snake_skin': { id: 'snake_skin', name: 'Yılan Derisi', quantity: 0, icon: 'https://files.catbox.moe/7g82to.png', type: 'material', rarity: 'common', description: 'Hafif ve esnek, deri zırh yapımında kullanılır.' },
    'poison_sac': { id: 'poison_sac', name: 'Zehir Kesesi', quantity: 0, icon: 'https://files.catbox.moe/fhc9r2.png', type: 'material', rarity: 'common', description: 'Yılanın zehrini barındıran organ. Silahları zehirlemek için kullanılabilir.' },
    'torn_map_piece': { id: 'torn_map_piece', name: 'Yırtık Harita Parçası', quantity: 0, icon: 'https://files.catbox.moe/dw5btd.png', type: 'material', rarity: 'common', description: 'Eski bir haritanın bir parçası. Diğer parçalar nerede acaba?' },
    'chicken_meat': { id: 'chicken_meat', name: 'Tavuk Eti', quantity: 0, icon: 'https://files.catbox.moe/lm0gz3.png', type: 'material', rarity: 'common', description: 'Basit ama doyurucu bir yiyecek.' },
    'cooked_chicken_meat': { id: 'cooked_chicken_meat', name: 'Pişmiş Tavuk Eti', quantity: 0, icon: 'https://files.catbox.moe/31ssxa.png', type: 'potion', rarity: 'common', healAmount: 0.20, description: 'Hafif bir öğün. Canın %20\'sini yeniler.' },
    'chicken_feather': { id: 'chicken_feather', name: 'Tavuk Tüyü', quantity: 0, icon: 'https://files.catbox.moe/pq0h8r.png', type: 'material', rarity: 'common', description: 'Ok yapımı ve süslemeler için kullanılır.' },
    'chicken_egg': { id: 'chicken_egg', name: 'Tavuk Yumurtası', quantity: 0, icon: 'https://files.catbox.moe/pq0h8r.png', type: 'material', rarity: 'common', description: 'Besleyici ve çok yönlü bir gıda maddesi.' },
    'healing_herb': { id: 'healing_herb', name: 'İyileştirici Bitki', quantity: 0, icon: 'https://files.catbox.moe/yeqx70.png', type: 'potion', rarity: 'common', healAmount: 0.10, description: 'Doğada bulunan, hafif yaraları iyileştirme özelliğine sahip yaygın bir bitki.' },
    'bear_pelt': { id: 'bear_pelt', name: 'Ayı Postu', quantity: 0, icon: 'https://files.catbox.moe/ixz5p1.png', type: 'material', rarity: 'uncommon', description: 'Kalın ve sıcak tutan bu post, soğuk iklimler için zırh yapımında değerlidir.' },
    'raw_cow_meat': { id: 'raw_cow_meat', name: 'Çiğ İnek Eti', quantity: 0, icon: 'https://files.catbox.moe/34ntd1.png', type: 'material', rarity: 'common', description: 'Pişirildiğinde mükemmel bir ziyafet olur.' },
    'cooked_cow_meat': { id: 'cooked_cow_meat', name: 'Biftek', quantity: 0, icon: 'https://files.catbox.moe/hysftx.png', type: 'potion', rarity: 'uncommon', healAmount: 0.30, description: 'Doyurucu bir et parçası. Canın %30\'unu yeniler.' },
    'deer_horn': { id: 'deer_horn', name: 'Geyik Boynuzu', quantity: 0, icon: 'https://files.catbox.moe/qinvyu.png', type: 'material', rarity: 'uncommon', description: 'Dekoratif amaçlar ve bazı özel silah kabzaları için kullanılır.' },
    'deer_meat': { id: 'deer_meat', name: 'Geyik Eti', quantity: 0, icon: 'https://files.catbox.moe/wwf77b.png', type: 'material', rarity: 'uncommon', description: 'Az yağlı ve lezzetli bir avcı yemeği.' },
    'cooked_deer_meat': { id: 'cooked_deer_meat', name: 'Pişmiş Geyik Eti', quantity: 0, icon: 'https://files.catbox.moe/31ssxa.png', type: 'potion', rarity: 'uncommon', healAmount: 0.30, description: 'Avcının favorisi. Canın %30\'unu yeniler.' },
    'deer_pelt': { id: 'deer_pelt', name: 'Geyik Postu', quantity: 0, icon: 'https://files.catbox.moe/46f28e.png', type: 'material', rarity: 'uncommon', description: 'Hafif zırhlar ve giysiler için kullanılan yumuşak bir deri.' },
    'boar_pelt': { id: 'boar_pelt', name: 'Yaban Domuzu Postu', quantity: 0, icon: 'https://files.catbox.moe/ufn109.png', type: 'material', rarity: 'uncommon', description: 'Sert kıllarıyla bilinen, dayanıklı bir post.' },
    'raw_boar_meat': { id: 'raw_boar_meat', name: 'Çiğ Yaban Domuzu Eti', quantity: 0, icon: 'https://files.catbox.moe/n7wjyv.png', type: 'material', rarity: 'uncommon', description: 'Güçlü ve yoğun bir tada sahip et.' },
    'cooked_boar_meat': { id: 'cooked_boar_meat', name: 'Pişmiş Yaban Domuzu Eti', quantity: 0, icon: 'https://files.catbox.moe/n7wjyv.png', type: 'potion', rarity: 'rare', healAmount: 0.40, description: 'Sert ama besleyici bir yemek. Canın %40\'ını yeniler.' },
    'ivory': { id: 'ivory', name: 'Fildişi', quantity: 0, icon: 'https://files.catbox.moe/kjcheu.png', type: 'material', rarity: 'rare', description: 'Değerli ve oyması zor bir malzeme, genellikle lüks eşyalarda kullanılır.' },
    'bat_wing': { id: 'bat_wing', name: 'Yarasa Kanadı', quantity: 0, icon: 'https://files.catbox.moe/o7jtis.png', type: 'material', rarity: 'uncommon', description: 'Uçuş iksirleri ve diğer alengirli simya karışımlarının vazgeçilmez bir parçası.' },
    'spider_web': { id: 'spider_web', name: 'Örümcek Ağı', quantity: 0, icon: 'https://files.catbox.moe/8rtv6t.png', type: 'material', rarity: 'uncommon', description: 'Şaşırtıcı derecede güçlü ve yapışkan, sağlam ipler ve kumaşlar yapmak için kullanılır.' },
    'wolf_pelt': { id: 'wolf_pelt', name: 'Kurt Postu', quantity: 0, icon: 'https://files.catbox.moe/tq9b31.png', type: 'material', rarity: 'rare', description: 'Hem sıcak tutan hem de vahşi bir görünüm veren, saygı duyulan bir avcının ganimeti.' },
    'griffon_feather': { id: 'griffon_feather', name: 'Griffon Tüyü', quantity: 0, icon: 'https://files.catbox.moe/tvgtlu.png', type: 'material', rarity: 'epic', description: 'Efsanevi Griffon\'dan düşen bu tüy, hafifliği ve dayanıklılığıyla bilinir. En iyi okların yapımında kullanılır.' },
    'sharp_claw': { id: 'sharp_claw', name: 'Keskin Pençe', quantity: 0, icon: 'https://files.catbox.moe/q93hjp.png', type: 'material', rarity: 'epic', description: 'Bir avcının pençesinden alınmış, kemiği bile çizebilecek kadar keskin.' },
    'goblin_king_crown': { id: 'goblin_king_crown', name: 'Goblin Kralının Tacı', quantity: 0, icon: 'https://files.catbox.moe/m4az0e.png', type: 'material', rarity: 'epic', description: 'Paslı çiviler ve parlak çakıl taşlarından yapılmış, bir goblin için statü sembolü.' },
    'ruh_esansi': { id: 'ruh_esansi', name: 'Ruh Esansı', quantity: 0, icon: 'https://files.catbox.moe/3earis.png', type: 'material', rarity: 'rare', description: 'Yenilmiş güçlü düşmanların geride bıraktığı, yoğunlaşmış ruhsal enerji.' },
    'lanet_tozu': { id: 'lanet_tozu', name: 'Lanet Tozu', quantity: 0, icon: 'https://files.catbox.moe/uw8ot9.png', type: 'material', rarity: 'common', description: 'Lanetlenmiş topraklardan toplanan, dokunana kötü şans getirdiği söylenen ince bir toz.' },
    'oz_tozu': { id: 'oz_tozu', name: 'Öz Tozu', quantity: 0, icon: 'https://files.catbox.moe/uw8ot9.png', type: 'material', rarity: 'uncommon', description: 'Simyasal reaksiyonları hızlandırmak için kullanılan parıldayan bir toz.' },
    'ruh_tozu': { id: 'ruh_tozu', name: 'Ruh Tozu', quantity: 0, icon: 'https://files.catbox.moe/l26h1h.png', type: 'material', rarity: 'rare', description: 'Hayaletimsi kalıntılardan elde edilen, ekipmanları efsunlamak için kullanılan ince bir toz.' },
    
    // === POTIONS ===
    'basic_health_potion': { id: 'basic_health_potion', name: 'Basit Can İksiri', quantity: 0, icon: 'https://files.catbox.moe/mle5l5.png', type: 'potion', rarity: 'common', healAmount: 0.25, description: 'Küçük yaraları iyileştiren standart bir karışım.' },
    'greater_health_potion': { id: 'greater_health_potion', name: 'Büyük Can İksiri', quantity: 0, icon: 'https://files.catbox.moe/09wew8.png', type: 'potion', rarity: 'uncommon', healAmount: 0.50, description: 'Ciddi yaralanmalarda hayat kurtarabilen, daha güçlü bir iyileştirme iksiri.' },

    // === SMELTED BARS ===
    'copper_bar': { id: 'copper_bar', name: 'Bakır Külçesi', quantity: 0, icon: 'https://files.catbox.moe/wt298r.png', type: 'material', rarity: 'common', description: 'Eritilmiş ve kalıplanmış bakır, zanaat için hazır.' },
    'iron_bar': { id: 'iron_bar', name: 'Demir Külçesi', quantity: 0, icon: 'https://files.catbox.moe/z3maeh.png', type: 'material', rarity: 'uncommon', description: 'Saflaştırılmış demir, daha güçlü ekipmanların temelini oluşturur.' },
    'steel_bar': { id: 'steel_bar', name: 'Çelik Külçesi', quantity: 0, icon: 'https://files.catbox.moe/z3maeh.png', type: 'material', rarity: 'uncommon', description: 'Sertleştirilmiş demir, profesyonel zırhlar ve silahlar için bir standart.' },
    'rom_bar': { id: 'rom_bar', name: 'Rom Külçesi', quantity: 0, icon: 'https://files.catbox.moe/uprmnu.png', type: 'material', rarity: 'rare', description: 'Işığı garip bir şekilde emen, Rom metallerinden yapılmış ağır bir külçe.' },
    'ent_bar': { id: 'ent_bar', name: 'Ent Külçesi', quantity: 0, icon: 'https://files.catbox.moe/2xiha4.png', type: 'material', rarity: 'rare', description: 'Hem metalin sertliğine hem de ahşabın esnekliğine sahip, dövülmesi zor bir malzeme.' },
    'kingdom_bar': { id: 'kingdom_bar', name: 'Krallık Külçesi', quantity: 0, icon: 'https://files.catbox.moe/uprmnu.png', type: 'material', rarity: 'epic', description: 'Parlaklığı göz kamaştıran, en üst düzey ekipmanlar için ayrılmış saf bir metal.' },

    // === TIER 1: WORN / STARTER (Level 1) ===
    'worn_helmet': { id: 'worn_helmet', name: 'Eskipüskü Başlık', quantity: 0, icon: 'https://files.catbox.moe/65v3h0.png', type: 'equipment', equipmentType: 'helmet', rarity: 'common', stats: { endurance: 1 }, levelReq: 1, set: 'worn', description: 'En azından kafanı yağmurdan korur. Muhtemelen.' },
    'worn_chest': { id: 'worn_chest', name: 'Eskipüskü Göğüslük', quantity: 0, icon: 'https://files.catbox.moe/eb7ksd.png', type: 'equipment', equipmentType: 'chest', rarity: 'common', stats: { endurance: 2 }, levelReq: 1, set: 'worn', description: 'Daha iyi günleri görmüş bir zırh. Üzerindeki delikler hikaye anlatıyor.' },
    'worn_legs': { id: 'worn_legs', name: 'Dermeçatma Pantolon', quantity: 0, icon: 'https://files.catbox.moe/so56aj.png', type: 'equipment', equipmentType: 'legs', rarity: 'common', stats: { endurance: 1 }, levelReq: 1, set: 'worn', description: 'Farklı kumaş parçalarının bir araya getirilmesiyle yapılmış.' },
    'worn_gloves': { id: 'worn_gloves', name: 'Yırtılmış Eldiven', quantity: 0, icon: 'https://files.catbox.moe/krxtxw.png', type: 'equipment', equipmentType: 'gloves', rarity: 'common', stats: { strength: 1 }, levelReq: 1, set: 'worn', description: 'Parmakların görünüyor ama en azından avuçların nasır tutmaz.' },
    'worn_boots': { id: 'worn_boots', name: 'Eskipüskü Bot', quantity: 0, icon: 'https://files.catbox.moe/kgp4im.png', type: 'equipment', equipmentType: 'boots', rarity: 'common', stats: { agility: 1 }, levelReq: 1, set: 'worn', description: 'Tabanları delik deşik, ama hiç yoktan iyidir.' },
    'worn_shield': { id: 'worn_shield', name: 'Eskimiş Kalkan', quantity: 0, icon: 'https://files.catbox.moe/cwgv5t.png', type: 'equipment', equipmentType: 'shield', rarity: 'common', stats: { endurance: 2 }, levelReq: 1, description: 'Birkaç oka karşı koruma sağlayabilir, ama bir ejderhaya karşı pek şansı yok.' },
    'starter_sword': { id: 'starter_sword', name: 'Acemi Kılıcı', quantity: 0, icon: 'https://files.catbox.moe/sal0w1.png', type: 'equipment', equipmentType: 'weapon', rarity: 'common', stats: { strength: 3 }, levelReq: 1, description: 'Biraz yontulmuş basit bir tahta parçası. En azından sivri ucu var.' },
    'starter_bow': { id: 'starter_bow', name: 'Acemi Yayı', quantity: 0, icon: 'https://files.catbox.moe/b7fus0.png', type: 'equipment', equipmentType: 'weapon', rarity: 'common', stats: { agility: 3 }, levelReq: 1, description: 'Esnek bir dala bağlanmış bir ipten ibaret. Okları çok uzağa fırlatamaz.' },
    'worn_pickaxe': { id: 'worn_pickaxe', name: 'Eskipüskü Kazma', quantity: 0, icon: 'https://files.catbox.moe/avzrtl.png', type: 'equipment', equipmentType: 'tool', toolType: 'pickaxe', rarity: 'common', efficiencyBonus: 0.05, stats: {}, levelReq: 1, description: 'Taşı kırmak için defalarca vurmak gerekebilir.' },
    'worn_axe': { id: 'worn_axe', name: 'Eskipüskü Balta', quantity: 0, icon: 'https://files.catbox.moe/sxiwuu.png', type: 'equipment', equipmentType: 'tool', toolType: 'axe', rarity: 'common', efficiencyBonus: 0.05, stats: {}, levelReq: 1, description: 'Kör ama inatçı. Sonunda o ağacı devirecektir.' },
    'aged_fishing_rod': { id: 'aged_fishing_rod', name: 'Yıllanmış Olta', quantity: 0, icon: 'https://files.catbox.moe/1zim2p.png', type: 'equipment', equipmentType: 'tool', toolType: 'fishing_rod', rarity: 'common', efficiencyBonus: 0.05, stats: {}, levelReq: 1, description: 'Birçok balık görmüş, tecrübeli bir olta.' },

    // === TIER 2: COPPER (Level 5) ===
    'copper_helmet': { id: 'copper_helmet', name: 'Bakır Başlık', quantity: 0, icon: 'https://files.catbox.moe/p1nct5.png', type: 'equipment', equipmentType: 'helmet', rarity: 'common', stats: { endurance: 3 }, levelReq: 5, set: 'copper', description: 'Basit ama etkili bir koruma. Kafanı beladan uzak tutar.' },
    'copper_chest': { id: 'copper_chest', name: 'Bakır Göğüslük', quantity: 0, icon: 'https://files.catbox.moe/2i52o8.png', type: 'equipment', equipmentType: 'chest', rarity: 'common', stats: { endurance: 5 }, levelReq: 5, set: 'copper', description: 'Güvenilir bakırdan dövülmüş, hayati organlarını korur.' },
    'copper_legs': { id: 'copper_legs', name: 'Bakır Pantolon', quantity: 0, icon: 'https://files.catbox.moe/wvf4ds.png', type: 'equipment', equipmentType: 'legs', rarity: 'common', stats: { endurance: 4 }, levelReq: 5, set: 'copper', description: 'Hareket kabiliyetini engellemeden temel koruma sağlar.' },
    'copper_gloves': { id: 'copper_gloves', name: 'Bakır Eldiven', quantity: 0, icon: 'https://files.catbox.moe/xx6kg2.png', type: 'equipment', equipmentType: 'gloves', rarity: 'common', stats: { strength: 2 }, levelReq: 5, set: 'copper', description: 'Silahını daha sıkı kavramanı sağlar.' },
    'copper_boots': { id: 'copper_boots', name: 'Bakır Bot', quantity: 0, icon: 'https://files.catbox.moe/mq3xro.png', type: 'equipment', equipmentType: 'boots', rarity: 'common', stats: { agility: 2 }, levelReq: 5, set: 'copper', description: 'Zorlu arazilerde adımlarını sağlamlaştırır.' },
    'copper_shield': { id: 'copper_shield', name: 'Bakır Kalkan', quantity: 0, icon: 'https://files.catbox.moe/q9bk1x.png', type: 'equipment', equipmentType: 'shield', rarity: 'common', stats: { endurance: 4 }, levelReq: 5, description: 'Hafif ve kullanışlı, acemi savaşçılar için mükemmel.' },
    'copper_sword': { id: 'copper_sword', name: 'Bakır Kılıç', quantity: 0, icon: 'https://files.catbox.moe/7lhdz2.png', type: 'equipment', equipmentType: 'weapon', rarity: 'common', stats: { strength: 6 }, levelReq: 5, description: 'Güvenilir bakırdan dövülmüş, yeni başlayan bir maceracı için ideal.' },
    'copper_bow': { id: 'copper_bow', name: 'Bakır Yay', quantity: 0, icon: 'https://files.catbox.moe/5fsca1.png', type: 'equipment', equipmentType: 'weapon', rarity: 'common', stats: { agility: 6 }, levelReq: 5, description: 'Ahşap yaydan daha isabetli ve güçlü.' },

    // === TIER 3: IRON (Level 10) ===
    'iron_helmet': { id: 'iron_helmet', name: 'Demir Başlık', quantity: 0, icon: 'https://files.catbox.moe/41a48a.png', type: 'equipment', equipmentType: 'helmet', rarity: 'uncommon', stats: { endurance: 5 }, levelReq: 10, set: 'iron', description: 'Savaşın zorluklarına dayanacak şekilde tasarlanmış sağlam bir miğfer.' },
    'iron_chest': { id: 'iron_chest', name: 'Demir Göğüslük', quantity: 0, icon: 'https://files.catbox.moe/xhxqz5.png', type: 'equipment', equipmentType: 'chest', rarity: 'uncommon', stats: { endurance: 8 }, levelReq: 10, set: 'iron', description: 'Demir plakalarla güçlendirilmiş, ciddi bir koruma sağlar.' },
    'iron_legs': { id: 'iron_legs', name: 'Demir Pantolon', quantity: 0, icon: 'https://files.catbox.moe/xq5638.png', type: 'equipment', equipmentType: 'legs', rarity: 'uncommon', stats: { endurance: 6 }, levelReq: 10, set: 'iron', description: 'Savaş alanında tecrübe kazanmış savaşçıların tercihi.' },
    'iron_gloves': { id: 'iron_gloves', name: 'Demir Eldiven', quantity: 0, icon: 'https://files.catbox.moe/5y6m3f.png', type: 'equipment', equipmentType: 'gloves', rarity: 'uncommon', stats: { strength: 4 }, levelReq: 10, set: 'iron', description: 'Darbelerin gücünü artıran, demir levhalı eldivenler.' },
    'iron_boots': { id: 'iron_boots', name: 'Demir Bot', quantity: 0, icon: 'https://files.catbox.moe/xqrxfw.png', type: 'equipment', equipmentType: 'boots', rarity: 'uncommon', stats: { agility: 4 }, levelReq: 10, set: 'iron', description: 'Ağır ama koruyucu, her türlü darbeye karşı dayanıklıdır.' },
    'iron_shield': { id: 'iron_shield', name: 'Demir Kalkan', quantity: 0, icon: 'https://files.catbox.moe/gytd3l.png', type: 'equipment', equipmentType: 'shield', rarity: 'uncommon', stats: { endurance: 7 }, levelReq: 10, description: 'Savaşta kendini kanıtlamış, güvenilir bir savunma aracı.' },
    'iron_sword': { id: 'iron_sword', name: 'Demir Kılıç', quantity: 0, icon: 'https://files.catbox.moe/2tdi1k.png', type: 'equipment', equipmentType: 'weapon', rarity: 'uncommon', stats: { strength: 10 }, levelReq: 10, description: 'Savaşta kendini kanıtlamış demirden yapılmış, sağlam ve keskin.' },
    'iron_bow': { id: 'iron_bow', name: 'Demir Yay', quantity: 0, icon: 'https://files.catbox.moe/yiwoek.png', type: 'equipment', equipmentType: 'weapon', rarity: 'uncommon', stats: { agility: 10 }, levelReq: 10, description: 'Demirle güçlendirilmiş bu yay, okları daha uzağa ve daha hızlı fırlatır.' },

    // === TIER 4: STEEL (Level 15) ===
    'steel_helmet': { id: 'steel_helmet', name: 'Çelik Başlık', quantity: 0, icon: 'https://files.catbox.moe/jvmmyh.png', type: 'equipment', equipmentType: 'helmet', rarity: 'uncommon', stats: { endurance: 7, tactics: 1 }, levelReq: 15, set: 'steel', description: 'Usta bir demircinin elinden çıkmış, hem koruyucu hem de gösterişli.' },
    'steel_chest': { id: 'steel_chest', name: 'Çelik Göğüslük', quantity: 0, icon: 'https://files.catbox.moe/j1gc8y.png', type: 'equipment', equipmentType: 'chest', rarity: 'uncommon', stats: { endurance: 11, tactics: 2 }, levelReq: 15, set: 'steel', description: 'Parlatılmış çelikten yapılmış, düşmanlara korku salan bir zırh.' },
    'steel_legs': { id: 'steel_legs', name: 'Çelik Pantolon', quantity: 0, icon: 'https://files.catbox.moe/x2i02k.png', type: 'equipment', equipmentType: 'legs', rarity: 'uncommon', stats: { endurance: 9, tactics: 1 }, levelReq: 15, set: 'steel', description: 'Mükemmel işçiliğiyle hem koruma hem de esneklik sunar.' },
    'steel_gloves': { id: 'steel_gloves', name: 'Çelik Eldiven', quantity: 0, icon: 'https://files.catbox.moe/ahlmmx.png', type: 'equipment', equipmentType: 'gloves', rarity: 'uncommon', stats: { strength: 6 }, levelReq: 15, set: 'steel', description: 'Her parmağı koruyan, hassas ve güçlü bir tasarım.' },
    'steel_boots': { id: 'steel_boots', name: 'Çelik Bot', quantity: 0, icon: 'https://files.catbox.moe/x07jra.png', type: 'equipment', equipmentType: 'boots', rarity: 'uncommon', stats: { agility: 6 }, levelReq: 15, set: 'steel', description: 'Altı çivili bu botlar, en kaygan zeminlerde bile tutunur.' },
    'steel_shield': { id: 'steel_shield', name: 'Çelik Kalkan', quantity: 0, icon: 'https://files.catbox.moe/ke1xzt.png', type: 'equipment', equipmentType: 'shield', rarity: 'uncommon', stats: { endurance: 10, tactics: 2 }, levelReq: 15, description: 'Üzerindeki armasıyla sahibinin cesaretini simgeler.' },
    'steel_sword': { id: 'steel_sword', name: 'Çelik Kılıç', quantity: 0, icon: 'https://files.catbox.moe/ewfdi1.png', type: 'equipment', equipmentType: 'weapon', rarity: 'uncommon', stats: { strength: 15 }, levelReq: 15, description: 'Usta bir demircinin elinden çıkmış, dengeli ve ölümcül bir çelik kılıç.' },
    'steel_bow': { id: 'steel_bow', name: 'Çelik Yay', quantity: 0, icon: 'https://files.catbox.moe/yiwoek.png', type: 'equipment', equipmentType: 'weapon', rarity: 'uncommon', stats: { agility: 15 }, levelReq: 15, description: 'Gerilmesi zor ama fırlattığı oklar bir zırhı delebilir.' },

    // === TIER 5: ROM (Level 20) ===
    'rom_helmet': { id: 'rom_helmet', name: 'Rom Başlığı', quantity: 0, icon: 'https://files.catbox.moe/wtrid9.png', type: 'equipment', equipmentType: 'helmet', rarity: 'rare', stats: { endurance: 10, luck: 2 }, levelReq: 20, set: 'rom', description: 'Rom metallerinin gizemli enerjisiyle parıldayan bir başlık.' },
    'rom_chest': { id: 'rom_chest', name: 'Rom Göğüslük', quantity: 0, icon: 'https://files.catbox.moe/epicw5.png', type: 'equipment', equipmentType: 'chest', rarity: 'rare', stats: { endurance: 15, luck: 3 }, levelReq: 20, set: 'rom', description: 'Bu zırhın, sahibine beklenmedik bir şans getirdiği söylenir.' },
    'rom_legs': { id: 'rom_legs', name: 'Rom Pantolon', quantity: 0, icon: 'https://files.catbox.moe/4kaod2.png', type: 'equipment', equipmentType: 'legs', rarity: 'rare', stats: { endurance: 12, luck: 2 }, levelReq: 20, set: 'rom', description: 'Adımlarını hafifletir ve kaderin yollarında sana rehberlik eder.' },
    'rom_gloves': { id: 'rom_gloves', name: 'Rom Eldiveni', quantity: 0, icon: 'https://files.catbox.moe/ca02ch.png', type: 'equipment', equipmentType: 'gloves', rarity: 'rare', stats: { strength: 8, luck: 1 }, levelReq: 20, set: 'rom', description: 'Bu eldivenlerle tuttuğun her şey, altına dönüşmese de daha değerli hale gelir.' },
    'rom_boots': { id: 'rom_boots', name: 'Rom Ayakkabısı', quantity: 0, icon: 'https://files.catbox.moe/xfzkn4.png', type: 'equipment', equipmentType: 'boots', rarity: 'rare', stats: { agility: 8, luck: 1 }, levelReq: 20, set: 'rom', description: 'Seni her zaman doğru yola, hazineye götüren sihirli botlar.' },
    'rom_shield': { id: 'rom_shield', name: 'Rom Kalkanı', quantity: 0, icon: 'https://files.catbox.moe/gcob0r.png', type: 'equipment', equipmentType: 'shield', rarity: 'rare', stats: { endurance: 14, luck: 3 }, levelReq: 20, description: 'Üzerine gelen darbeleri sahibinden uzaklaştırıp kötü şansa çevirir.' },
    'rom_sword': { id: 'rom_sword', name: 'Rom Kılıcı', quantity: 0, icon: 'https://files.catbox.moe/ukq7st.png', type: 'equipment', equipmentType: 'weapon', rarity: 'rare', stats: { strength: 22 }, levelReq: 20, description: 'Rom çeliğinin gizemli gücünü barındıran, nadir bir silah.' },
    'rom_bow': { id: 'rom_bow', name: 'Rom Yayı', quantity: 0, icon: 'https://files.catbox.moe/bvln9m.png', type: 'equipment', equipmentType: 'weapon', rarity: 'rare', stats: { agility: 22 }, levelReq: 20, description: 'Bu yaydan çıkan okların hedefini asla şaşırmadığı rivayet edilir.' },
    
    // === TIER 6: ENT (Level 25) ===
    'ent_helmet': { id: 'ent_helmet', name: 'Ent Başlık', quantity: 0, icon: 'https://files.catbox.moe/axwbhu.png', type: 'equipment', equipmentType: 'helmet', rarity: 'rare', stats: { endurance: 14, strength: 3 }, levelReq: 25, set: 'ent', description: 'Canlı bir ağacın kabuğundan yapılmış, doğanın bilgeliğini fısıldar.' },
    'ent_chest': { id: 'ent_chest', name: 'Ent Göğüslük', quantity: 0, icon: 'https://files.catbox.moe/fgn779.png', type: 'equipment', equipmentType: 'chest', rarity: 'rare', stats: { endurance: 20, strength: 5 }, levelReq: 25, set: 'ent', description: 'Kadim ormanın gücünü içinde barındıran, yaşayan bir zırh.' },
    'ent_legs': { id: 'ent_legs', name: 'Ent Pantolon', quantity: 0, icon: 'https://files.catbox.moe/12qg88.png', type: 'equipment', equipmentType: 'legs', rarity: 'rare', stats: { endurance: 17, strength: 4 }, levelReq: 25, set: 'ent', description: 'Sarmaşıklar ve sağlam köklerle örülmüş, seni toprağa bağlar.' },
    'ent_gloves': { id: 'ent_gloves', name: 'Ent Eldiveni', quantity: 0, icon: 'https://files.catbox.moe/a9x4kb.png', type: 'equipment', equipmentType: 'gloves', rarity: 'rare', stats: { strength: 10, agility: 2 }, levelReq: 25, set: 'ent', description: 'Bu eldivenlerle doğanın gücünü ellerinde hissedersin.' },
    'ent_boots': { id: 'ent_boots', name: 'Ent Bot', quantity: 0, icon: 'https://files.catbox.moe/vgrhb7.png', type: 'equipment', equipmentType: 'boots', rarity: 'rare', stats: { agility: 10, strength: 2 }, levelReq: 25, set: 'ent', description: 'Adımlarını sessizleştirir ve ormanda iz bırakmadan yürümeni sağlar.' },
    'ent_shield': { id: 'ent_shield', name: 'Ent Kalkanı', quantity: 0, icon: 'https://files.catbox.moe/a2d115.png', type: 'equipment', equipmentType: 'shield', rarity: 'rare', stats: { endurance: 18, strength: 4 }, levelReq: 25, description: 'En yaşlı ağacın gövdesinden yapılmış, kırılması neredeyse imkansız.' },
    'ent_sword': { id: 'ent_sword', name: 'Ent Kılıcı', quantity: 0, icon: 'https://files.catbox.moe/icqrto.png', type: 'equipment', equipmentType: 'weapon', rarity: 'rare', stats: { strength: 30 }, levelReq: 25, description: 'Kadim Entlerin özünden yapılmış, doğanın gücüyle dolu bir kılıç.' },
    'ent_bow': { id: 'ent_bow', name: 'Ent Yayı', quantity: 0, icon: 'https://files.catbox.moe/rmipa6.png', type: 'equipment', equipmentType: 'weapon', rarity: 'rare', stats: { agility: 30 }, levelReq: 25, description: 'Yaşayan bir daldan yapılmış bu yay, fırlattığı oklara hayat verir.' },

    // === TIER 7: KINGDOM (Level 30) ===
    'kingdom_helmet': { id: 'kingdom_helmet', name: 'Krallık Kaskı', quantity: 0, icon: 'https://files.catbox.moe/bfri0o.png', type: 'equipment', equipmentType: 'helmet', rarity: 'epic', stats: { endurance: 18, tactics: 4, luck: 4 }, levelReq: 30, set: 'kingdom', description: 'Sadece krallığın en sadık şövalyelerinin giydiği, armalı bir kask.' },
    'kingdom_chest': { id: 'kingdom_chest', name: 'Krallık Zırhı', quantity: 0, icon: 'https://files.catbox.moe/sop1qa.png', type: 'equipment', equipmentType: 'chest', rarity: 'epic', stats: { endurance: 26, tactics: 6, luck: 6 }, levelReq: 30, set: 'kingdom', description: 'Krallık demircilerinin başyapıtı, hem bir sanat eseri hem de bir ölüm makinesi.' },
    'kingdom_legs': { id: 'kingdom_legs', name: 'Krallık Pantolonu', quantity: 0, icon: 'https://files.catbox.moe/udycf9.png', type: 'equipment', equipmentType: 'legs', rarity: 'epic', stats: { endurance: 22, tactics: 5, luck: 5 }, levelReq: 30, set: 'kingdom', description: 'Asil bir duruş ve eşsiz bir koruma sağlayan, işlemeli bir zırh parçası.' },
    'kingdom_gloves': { id: 'kingdom_gloves', name: 'Krallık Eldiveni', quantity: 0, icon: 'https://files.catbox.moe/a7w467.png', type: 'equipment', equipmentType: 'gloves', rarity: 'epic', stats: { strength: 14, agility: 4, tactics: 2 }, levelReq: 30, set: 'kingdom', description: 'Kraliyet mührüyle damgalanmış, sahibine büyük bir güç verir.' },
    'kingdom_boots': { id: 'kingdom_boots', name: 'Krallık Botu', quantity: 0, icon: 'https://files.catbox.moe/4bvjfx.png', type: 'equipment', equipmentType: 'boots', rarity: 'epic', stats: { agility: 14, strength: 4, tactics: 2 }, levelReq: 30, set: 'kingdom', description: 'Bu botlarla atılan her adım, bir krallığın ağırlığını taşır.' },
    'kingdom_shield': { id: 'kingdom_shield', name: 'Krallık Kalkanı', quantity: 0, icon: 'https://files.catbox.moe/aen949.png', type: 'equipment', equipmentType: 'shield', rarity: 'epic', stats: { endurance: 24, strength: 5, tactics: 5 }, levelReq: 30, description: 'Krallığın onurunu ve gücünü temsil eden, sarsılmaz bir kalkan.' },
    'kingdom_sword': { id: 'kingdom_sword', name: 'Krallık Kılıcı', quantity: 0, icon: 'https://files.catbox.moe/c2py7f.png', type: 'equipment', equipmentType: 'weapon', rarity: 'legendary', stats: { strength: 40, tactics: 5 }, levelReq: 30, description: 'Kralların emriyle, usta demirciler tarafından dövülmüş efsanevi bir kılıç.' },
    'kingdom_bow': { id: 'kingdom_bow', name: 'Krallık Yayı', quantity: 0, icon: 'https://files.catbox.moe/hdbqy2.png', type: 'equipment', equipmentType: 'weapon', rarity: 'legendary', stats: { agility: 40, tactics: 5 }, levelReq: 30, description: 'Ejderha kirişiyle gerilmiş, bu yaydan çıkan oklar adaleti temsil eder.' },

    // === RECIPE BOOKS ===
    // Rom
    'recipe_book_rom_helmet': { id: 'recipe_book_rom_helmet', name: 'Tarif: Rom Başlığı', quantity: 0, icon: 'https://files.catbox.moe/3uxgr8.png', type: 'misc', rarity: 'rare', description: 'Rom metallerinden nasıl başlık yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_rom_chest': { id: 'recipe_book_rom_chest', name: 'Tarif: Rom Göğüslük', quantity: 0, icon: 'https://files.catbox.moe/g4owvx.png', type: 'misc', rarity: 'rare', description: 'Rom metallerinden nasıl göğüslük yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_rom_legs': { id: 'recipe_book_rom_legs', name: 'Tarif: Rom Pantolon', quantity: 0, icon: 'https://files.catbox.moe/xgb1dk.png', type: 'misc', rarity: 'rare', description: 'Rom metallerinden nasıl pantolon yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_rom_gloves': { id: 'recipe_book_rom_gloves', name: 'Tarif: Rom Eldiveni', quantity: 0, icon: 'https://files.catbox.moe/ay0ruf.png', type: 'misc', rarity: 'rare', description: 'Rom metallerinden nasıl eldiven yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_rom_boots': { id: 'recipe_book_rom_boots', name: 'Tarif: Rom Ayakkabısı', quantity: 0, icon: 'https://files.catbox.moe/vbdw8f.png', type: 'misc', rarity: 'rare', description: 'Rom metallerinden nasıl ayakkabı yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_rom_shield': { id: 'recipe_book_rom_shield', name: 'Tarif: Rom Kalkanı', quantity: 0, icon: 'https://files.catbox.moe/n1taxi.png', type: 'misc', rarity: 'rare', description: 'Rom metallerinden nasıl kalkan yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_rom_sword': { id: 'recipe_book_rom_sword', name: 'Tarif: Rom Kılıcı', quantity: 0, icon: 'https://files.catbox.moe/icr46o.png', type: 'misc', rarity: 'rare', description: 'Rom metallerinden nasıl kılıç yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_rom_bow': { id: 'recipe_book_rom_bow', name: 'Tarif: Rom Yayı', quantity: 0, icon: 'https://files.catbox.moe/ymiuew.png', type: 'misc', rarity: 'rare', description: 'Rom metallerinden nasıl yay yapılacağını anlatan eski bir parşömen.' },

    // Ent
    'recipe_book_ent_helmet': { id: 'recipe_book_ent_helmet', name: 'Tarif: Ent Başlık', quantity: 0, icon: 'https://files.catbox.moe/3uxgr8.png', type: 'misc', rarity: 'rare', description: 'Ent metallerinden nasıl başlık yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_ent_chest': { id: 'recipe_book_ent_chest', name: 'Tarif: Ent Göğüslük', quantity: 0, icon: 'https://files.catbox.moe/g4owvx.png', type: 'misc', rarity: 'rare', description: 'Ent metallerinden nasıl göğüslük yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_ent_legs': { id: 'recipe_book_ent_legs', name: 'Tarif: Ent Pantolon', quantity: 0, icon: 'https://files.catbox.moe/xgb1dk.png', type: 'misc', rarity: 'rare', description: 'Ent metallerinden nasıl pantolon yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_ent_gloves': { id: 'recipe_book_ent_gloves', name: 'Tarif: Ent Eldiveni', quantity: 0, icon: 'https://files.catbox.moe/ay0ruf.png', type: 'misc', rarity: 'rare', description: 'Ent metallerinden nasıl eldiven yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_ent_boots': { id: 'recipe_book_ent_boots', name: 'Tarif: Ent Bot', quantity: 0, icon: 'https://files.catbox.moe/vbdw8f.png', type: 'misc', rarity: 'rare', description: 'Ent metallerinden nasıl bot yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_ent_shield': { id: 'recipe_book_ent_shield', name: 'Tarif: Ent Kalkanı', quantity: 0, icon: 'https://files.catbox.moe/n1taxi.png', type: 'misc', rarity: 'rare', description: 'Ent metallerinden nasıl kalkan yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_ent_sword': { id: 'recipe_book_ent_sword', name: 'Tarif: Ent Kılıcı', quantity: 0, icon: 'https://files.catbox.moe/icr46o.png', type: 'misc', rarity: 'rare', description: 'Ent metallerinden nasıl kılıç yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_ent_bow': { id: 'recipe_book_ent_bow', name: 'Tarif: Ent Yayı', quantity: 0, icon: 'https://files.catbox.moe/ymiuew.png', type: 'misc', rarity: 'rare', description: 'Ent metallerinden nasıl yay yapılacağını anlatan eski bir parşömen.' },
    
    // Kingdom
    'recipe_book_kingdom_helmet': { id: 'recipe_book_kingdom_helmet', name: 'Tarif: Krallık Kaskı', quantity: 0, icon: 'https://files.catbox.moe/3uxgr8.png', type: 'misc', rarity: 'epic', description: 'Krallık metallerinden nasıl kask yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_kingdom_chest': { id: 'recipe_book_kingdom_chest', name: 'Tarif: Krallık Zırhı', quantity: 0, icon: 'https://files.catbox.moe/g4owvx.png', type: 'misc', rarity: 'epic', description: 'Krallık metallerinden nasıl zırh yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_kingdom_legs': { id: 'recipe_book_kingdom_legs', name: 'Tarif: Krallık Pantolonu', quantity: 0, icon: 'https://files.catbox.moe/xgb1dk.png', type: 'misc', rarity: 'epic', description: 'Krallık metallerinden nasıl pantolon yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_kingdom_gloves': { id: 'recipe_book_kingdom_gloves', name: 'Tarif: Krallık Eldiveni', quantity: 0, icon: 'https://files.catbox.moe/ay0ruf.png', type: 'misc', rarity: 'epic', description: 'Krallık metallerinden nasıl eldiven yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_kingdom_boots': { id: 'recipe_book_kingdom_boots', name: 'Tarif: Krallık Botu', quantity: 0, icon: 'https://files.catbox.moe/vbdw8f.png', type: 'misc', rarity: 'epic', description: 'Krallık metallerinden nasıl bot yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_kingdom_shield': { id: 'recipe_book_kingdom_shield', name: 'Tarif: Krallık Kalkanı', quantity: 0, icon: 'https://files.catbox.moe/n1taxi.png', type: 'misc', rarity: 'epic', description: 'Krallık metallerinden nasıl kalkan yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_kingdom_sword': { id: 'recipe_book_kingdom_sword', name: 'Tarif: Krallık Kılıcı', quantity: 0, icon: 'https://files.catbox.moe/icr46o.png', type: 'misc', rarity: 'epic', description: 'Krallık metallerinden nasıl kılıç yapılacağını anlatan eski bir parşömen.' },
    'recipe_book_kingdom_bow': { id: 'recipe_book_kingdom_bow', name: 'Tarif: Krallık Yayı', quantity: 0, icon: 'https://files.catbox.moe/ymiuew.png', type: 'misc', rarity: 'epic', description: 'Krallık metallerinden nasıl yay yapılacağını anlatan eski bir parşömen.' },

};